FROM php:8.4-cli-alpine

RUN apk add --no-cache curl git unzip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer global require laravel/installer

ENV PATH="/root/.composer/vendor/bin:${PATH}"